spring:
  profiles:
    active: "dev"

---
spring:
  profiles: dev
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    platform: h2
    url: jdbc:h2:mem:jalal

---
spring:
  profiles: prod
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: on
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    password: 123
    username: root
    driver-class-name: com.mysql.jdbc.Driver
